name:                glados
version:             0.1.0.0
github:              "githubuser/glados"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/glados#readme>

dependencies:
- base >=4 && <5
- split >=0.2
- bytestring >= 0.11
- containers >=0.6
- data-binary-ieee754 ==0.4.4
- binary ==0.8.9.0
#- blip ==0.2.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  glados-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glados
    - split
    - containers
    - bytestring
    - binary
    - data-binary-ieee754
    #- blip

tests:
  glados-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glados
    - hspec
    - hspec-contrib
    - hspec-hedgehog
    - QuickCheck
