name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Installations for compilation
      run: curl -sSL https://get.haskellstack.org/ | sh
    - name: Install dependencies
      run: make
