name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Create missing file partial
      run: sudo mkdir -p /var/cache/apt/archives/partial
    - name: Install apt
      run: apt-get update --fix-missing
    - name: Installations for compilation stack
      run: curl -sSL https://get.haskellstack.org/ | sh
    - name: Install dependencies
      run: make
